<?php echo $this->doctype() ?>
<html>
<head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle() ?>
  <?php echo $this->headLink() ?>
</head>
<body>
<div class="navbar navbar-primary bg-info">
  <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="<?php echo $this->baseUrl()?>/forum/list">SFS</a>
        </div>
    <ul class="nav navbar-nav">
            <li><a href="<?php echo $this->baseUrl() ?>/forum/list">Home</a></li>
            <?php
              $user = Zend_Auth::getInstance();
        if($user->hasIdentity()) {
          $userObj = $user->getIdentity();
          if ($userObj->is_admin) {
      ?>
            <li><a href="<?php echo $this->baseUrl() ?>/users/admin">Admin Panel</a></li>
      <?php } } ?>
    </ul>
        <ul class="nav navbar-nav navbar-right">
            <?php
              $user = Zend_Auth::getInstance();
        if($user->hasIdentity()): ?>
            <li><span class="alert bg-primary"><img width="75" class='img-thumbnail img-circle' src="<?php echo $this->baseUrl(); ?>/user-uploads/<?php echo $user->getIdentity()->picture; ?>"/> <?php echo strtoupper($user->getIdentity()->username); ?></span></li>
            <li><a href="<?php echo $this->baseUrl()?>/user/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
            <?php else : ?>
              <li><a href="<?php echo $this->baseUrl()?>/user/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="<?php echo $this->baseUrl()?>/user/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            <?php endif;  ?>
        </ul>
  </div>
</div>
<div class="container col-sm-10 col-sm-offset-1">
  <div class="alert alert-success">
    &nbsp;  &nbsp;<?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render(); ?>
  </div>
  <hr>
  <?php echo $this->layout()->content; ?>
</div>
<div class="modal fade" id="editModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Edit Post</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label for="title" class="col-sm-2 control-label">Title</label>
          <div class="col-sm-10">
            <input type="text" id="title" class="form-control" value="" required="required">
          </div>
        </div>
        <div class="form-group">
          <label for="body" class="col-sm-2 control-label">Body</label>
          <div class="col-sm-10">
            <textarea id="body" class="form-control" rows="3" required="required"></textarea>
          </div>
        </div>
        <input type="hidden" id="id" class="form-control" value="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" id="savePost" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
  <?php echo $this->headScript() ?>
</body>
</html>
