<?php
	// javascript file to handle the edit functionality
	$this->headScript()->appendFile($this->baseUrl().'/js/ajax_delete_thread.js');
	$this->headScript()->appendFile($this->baseUrl().'/js/ajax_edit_thread.js');
	$this->headScript()->appendFile($this->baseUrl().'/js/ajax_add_reply.js');
	$this->headScript()->appendFile($this->baseUrl().'/js/ajax_delete_reply.js');
	$this->headScript()->appendFile($this->baseUrl().'/js/ajax_edit_reply.js');
	// echo $this->headTitle()->append($this->thread[0]['title']);
?>
<hr>
<div class="panel panel-primary">
	<div class="panel-heading" style="height:70px;">
		<div class="col-sm-1">
			<img src="<?php echo $this->baseUrl(); ?>/user-uploads/<?php echo $this->thread[0]['picture']; ?>" width='75' class='img-thumbnail img-circle' title ="<?php echo $this->thread[0]['username'] ?>" />
		</div>
		<h3 class="panel-title">
			<div class="col-sm-11">
				<strong id="title<?php echo $this->thread[0]['thread_id'] ?>"><?php echo $this->thread[0]['title'] ?></strong><br><br><p>Posted By : <?php echo strtoupper($this->thread[0]['username']); ?> | On: <?php echo $this->thread[0]['creation_date'];
					if ($lastUpdate = $this->thread[0]['last_update_date']): ?>
					| Last Update : <?php echo $lastUpdate; ?>
				<?php endif; ?> </p></h3>

			</div>
	</div>
	<div class="panel-body">
		<p id="body<?php echo $this->thread[0]['thread_id'] ?>"><?php echo $this->thread[0]['body'] ?></p>
		<hr class="bg-primary" style="height:2px;width:95%;">
		<h3 class="text-center text-primary">Signature</h3>
		<div class="badge col-sm-12">
			<div class="col-sm-12" style="height:25px;"></div><br>
			<div class="col-sm-12">
				<?php echo $this->thread[0]['signature']; ?>
			</div>
			<div class="col-sm-12" style="height:25px;"></div><br>
		</div>
	</div>
	<?php
		$user = Zend_Auth::getInstance();
		if ($user->hasIdentity()) :
			$userObj = $user->getIdentity();
			if ($this->thread[0]['creator'] == $userObj->u_id || $userObj->is_admin) :
	?>
	<div class="panel-footer">
		<a href="#editModal" data-toggle="modal" id="<?php echo $this->thread[0]['thread_id'] ?>" class="btn btn-warning edit" >Edit</a>
		<a id="delete<?php echo $this->thread[0]['thread_id']; ?>" name='detail-delete' class="btn btn-danger delete-thread">Delete</a>
	</div>
	<?php
		endif;
			endif;
	 ?>
	 <br>
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">Replies (<u id="rplsCount"><?php echo count($this->replies) ?></u>)</h3>
		</div>
		<div class="panel-body">
		<div id="repliesArea">
			<?php
			if (!count($this->replies)): ?>
				<div class="alert alert-warning" id='noRpls' >
					<strong>No Replies Yet</strong>
				</div>
			<?php else:
			foreach ($this->replies as $reply) : ?>
				<div>
					<div class="col-sm-offset-1 col-sm-10 panel panel-warning">
						<div class="panel-heading">
							<?php echo 'By :'.$reply['username'].' | On : '.$reply['creation_date']?>
						</div>
						<div class="panel-body" id="rplyCntnt<?php echo $reply['id']?>">
							<?php echo $reply['body']; ?>
						</div>
					</div>
					<?php
						$user = Zend_Auth::getInstance();
						if ($user->hasIdentity()) :
							$userObj = $user->getIdentity();
							if ($reply['replier_id'] == $userObj->u_id || $userObj->is_admin) :
					?>
					<div class="col-sm-1">
						<a id="delete-rply<?php echo $reply['id'] ?>" class="delete-rply btn glyphicon glyphicon-remove" style="font-size:1.5em;color:red;"></a>
					</div>
					<div class="col-sm-1">
						<a id="edit-rply<?php echo $reply['id'] ?>" class="edit-rply btn glyphicon glyphicon-pencil" style="font-size:1.5em;"></a>
					</div>
					<?php
						endif;
							endif;
					?>
				</div>
			<?php endforeach; endif; ?>
			<?php
				$user = Zend_Auth::getInstance();
				if ($user->hasIdentity()) :
			?>
		</div>
			<div class="form-group">
				<label for="textarea" class="col-sm-2 control-label">Reply</label>
				<div class="col-sm-10">
					<textarea name="" id="replyBody" class="form-control" rows="3" required="required"></textarea>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-10 col-offset-2">
					<button class="btn btn-primary reply" id="reply<?php echo $this->thread[0]['thread_id'] ?>">Reply</button>
				</div>
			</div>
		</div>
		<?php endif; ?>
	</div>
	 <input type="hidden" class="hidden" id="forum_id" value="<?php echo $this->thread[0]['forum_id']; ?>">
</div>
