
<?php
    // javascript file to handle the edit functionality
    // $this->headScript()->appendFile($this->baseUrl().'/js/edit.js');
    // if (count($this->threads) == 0)
    if (!count($this->paginator)) : ?>
		<div class="well well-sm">
			There Is No Threads To List :(
		</div>
		<?php else :
    	foreach ($this->paginator as $thread) : ?>
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title" id="title<?php echo $thread['thread_id'] ?>"><?php echo $thread['title'] ?></h3><small>Created By : <?php echo $thread['username']?> | On: <?php echo $thread['creation_date']?></small>
			</div>
			<div class="panel-body" id="body<?php echo $thread['thread_id'] ?>">
				<?php echo $thread['body'] ?>
			</div>
			<div class="panel-footer">
				<?php
                    $user = Zend_Auth::getInstance();
                    if ($user->hasIdentity()):
                        $userObj = $user->getIdentity();
                        if ($thread['u_id'] == $userObj->id || $userObj->is_admin):
                            ?>
				<a href="#editModal" data-toggle="modal" id="<?php echo $thread['id'] ?>" class="btn btn-warning edit">Edit</a>
				<a class="btn btn-danger delete-thread">Delete</a>
        <?php
          $user = Zend_Auth::getInstance();
          if ($user->hasIdentity()):
              $userObj = $user->getIdentity();
              if ($userObj->is_admin): ?>
                <a class="btn btn-default delete-thread">Pin</a>
        <?php endif; endif; ?>
				<?php
												endif;
										endif;
				?>
				<a href="<?php echo $this->baseUrl() ?>/threads/detail/id/<?php echo $thread['thread_id'] ?>" class="btn btn-info">Detail</a>
			</div>
		</div>
<?php
    endforeach;
endif;
echo $this->paginator;
?>
