<?php echo $this->partial('admin/index.phtml');?>

	<h3><code>Edit Forum</code></h3>

	<form method="post">

  <div class="container">

		<div class="form-group">
						<label class="control-label col-sm-2" for="title"></label>
						<div class="col-sm-10">
										<?php echo $this->form->cat_id ?>
						</div>
					</div>
					<br>

				<div class="form-group">
				    		<label class="control-label col-sm-2" for="title"></label>
				    		<div class="col-sm-10">
				      		      <?php echo $this->form->name ?>
				    		</div>
				    	</div>

							<div class="form-group">
											<label class="control-label col-sm-2" for="title"></label>
											<div class="col-sm-10">
															<?php echo $this->form->is_locked ?>
															<?php echo $this->form->save ?>
											</div>
										</div>

						</div> <!-- Container -->
</form>
