<?php echo $this->partial('admin/index.phtml'); ?>


<div class="container">
	<h3><code>List all Forums</code></h3>
	<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>ID</th>
    <th>Forum Name</th>
		<th>Category Name</th>
    <th>Actions</th>
  </tr>
  </thead>

 <?php
					if (count($this->paginator)) :
						foreach ($this->paginator as $forums) :
                ?>

          <tr>
          <td><?php echo $forums['id'] ?></td>
					<td><?php echo $forums['name'] ?></td>
					<td><?php echo $forums['cat_name'] ?></td>

  				<td>
            <a href="<?php echo $this->baseUrl();?>/forum/editforum/id/<?php echo ($forums['id']) ?>" class='btn btn-info' role='button'>Edit</a>
            <a href="<?php echo $this->baseUrl();?>/forum/deleteforum/id/<?php echo ($forums['id']) ?>" class="btn btn-danger"> Delete</a>

          </td>
          </tr>
  <?php
	endforeach;
	endif;
	?>



</table>
</div>
<?php echo $this->paginator; ?>
