<?php echo $this->partial('admin/index.phtml'); ?>


<div class="container">
	<h3><code>List all Forums</code></h3>
	<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>ID</th>
    <th>Forum Name</th>
		<th>Category Name</th>
    <th>Actions</th>
  </tr>
  </thead>

 <?php
      if ($this->forums){
  			for($i=0; $i<count($this->forums); $i++){

                ?>

          <tr>
          <td><?php echo $this->forums[$i]['id'] ?></td>
          <td><?php echo $this->spec[$i]['name'] ?></td>
					<td><?php echo $this->forums[$i]['name'] ?></td>

  				<td>
            <a href="<?php echo $this->baseUrl();?>/forum/editforum/id/<?php echo ($this->forums[$i]['id']) ?>" class='btn btn-info' role='button'>Edit</a>
            <a href="<?php echo $this->baseUrl();?>/forum/deleteforum/id/<?php echo ($this->forums[$i]['id']) ?>" class="btn btn-danger"> Delete</a>

          </td>
          </tr>
  <?php

	} //whiles

	    }

	?>



</table>
</div>
