<div class="container">
			<h1><code>Welcome Admin !!</code></h1>

			<ul class="nav nav-tabs">
				  <li><a href="<?php echo $this->baseUrl(); ?>/admin/index">Users</a></li>
				  <li class="active"><a href="<?php echo $this->baseUrl(); ?>/category/addcategory">Add Category</a></li>
				  <li><a href="<?php echo $this->baseUrl(); ?>/posts/list">list posts</a></li>
				  <li><a href="#">list comments</a></li>
			</ul>

			<h3><code>Users</code></h3>
</div>

<?php

echo $this->form;

?>
