<?php echo $this->partial('admin/index.phtml'); ?>


<div class="container">
	<h3><code>List all categories</code></h3>
	<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Actions</th>
  </tr>
  </thead>

 <?php
      if ($this->listcat){
  			for($i=0; $i<count($this->listcat); $i++){

                ?>

          <tr>
          <td><?php echo $this->listcat[$i]['cat_id'] ?></td>
          <td><?php echo $this->listcat[$i]['cat_name'] ?></td>

  				<td>
            <a href="<?php echo $this->baseUrl();?>/category/editcategories/id/<?php echo ($this->listcat[$i]['cat_id']) ?>" class='btn btn-info' role='button'>Edit</a>
            <a href="<?php echo $this->baseUrl();?>/category/deletecategories/id/<?php echo ($this->listcat[$i]['cat_id']) ?>" class="btn btn-danger"> Delete</a>
						<a href="<?php echo $this->baseUrl();?>/forum/addforum/?>" class="btn btn-success"> Add Forum </a>

          </td>
          </tr>
  <?php

	} //whiles

	    }

	?>



</table>
</div>
